#ifndef RETURN_CODE_H
#define RETURN_CODE_H

#define SUCCESS (0)
#define ERROR_OF_MEMORY (1)
#define ELEMENT_NOT_FOUND (2)
#define TABLE_IS_EMPTY (3)
#define TABLE_KEY_SPACE_NOT_INITIALIZE (4)
#define RELEASE_IS_EXISTS (5)
#define FILE_CAN_NOT_OPEN (6)
#define FILE_IS_END (EOF)
#define INVALID_FILE_CONTENT (7)
#define ERROR_IN_FILE (8)
#define INVALID_ARGUMENT (9)
#define INVALID_ARGUMENT_BY_INDEX(index) (INVALID_ARGUMENT + (index))

#endif // RETURN_CODE_H